DROP DATABASE IF EXISTS inventario;
CREATE DATABASE inventario CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE inventario;
CREATE TABLE Categories (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE Locations (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL UNIQUE,
Description VARCHAR(255) NULL
);
CREATE TABLE Users (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL UNIQUE,
PasswordHash VARCHAR(255) NOT NULL,
Role VARCHAR(20) NOT NULL DEFAULT 'Technician'
);
CREATE TABLE Equipments (
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(150) NOT NULL,
SerialNumber VARCHAR(100) NOT NULL UNIQUE,
Brand VARCHAR(100) NULL,
Model VARCHAR(100) NULL,
Status VARCHAR(20) NOT NULL DEFAULT 'Available',
PurchaseDate DATE NULL,
Price DECIMAL(10,2) NULL,
Notes TEXT NULL,
CategoryId INT NOT NULL,
LocationId INT NOT NULL,
CONSTRAINT FK_Equipments_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
CONSTRAINT FK_Equipments_Locations FOREIGN KEY (LocationId) REFERENCES Locations(Id)
);
CREATE TABLE Movements (
Id INT AUTO_INCREMENT PRIMARY KEY,
EquipmentId INT NOT NULL,
Type VARCHAR(20) NOT NULL,
Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FromLocationId INT NULL,
ToLocationId INT NULL,
AssignedTo VARCHAR(100) NULL,
Notes VARCHAR(500) NULL,
UserId INT NULL,
CONSTRAINT FK_Movements_Equipments FOREIGN KEY (EquipmentId) REFERENCES Equipments(Id) ON
DELETE CASCADE,
CONSTRAINT FK_Movements_FromLoc FOREIGN KEY (FromLocationId) REFERENCES Locations(Id),
CONSTRAINT FK_Movements_ToLoc FOREIGN KEY (ToLocationId) REFERENCES Locations(Id),
CONSTRAINT FK_Movements_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
